param(
  [ValidateSet("Full", "ReferencesOnly")]
  [string]$Mode = "Full",
  [string]$StartDate,
  [string]$StopDate,
  [int]$DelayMs = 250,
  [switch]$NormalizeExistingTimeScale
)

$ErrorActionPreference = "Stop"
$Invariant = [Globalization.CultureInfo]::InvariantCulture
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$CatalogPath = Join-Path $Root "js\deep-space-catalog.js"
$OutputPath = Join-Path $Root "js\deep-space-ephemeris.js"

function Get-ObjectProperty([object]$Object, [string]$Name) {
  if ($null -eq $Object) { return $null }
  $Property = $Object.PSObject.Properties[$Name]
  if ($null -eq $Property) { return $null }
  return $Property.Value
}

# Horizons vector epochs are JDTDB. JavaScript Date values are UTC instants,
# so treating the numeric JD as a Unix/UTC timestamp makes every state about
# 69 seconds early in the current era. Keep a local leap-second table and the
# standard millisecond-level TDB-TT periodic approximation so the generated
# bundle carries real UTC instants while retaining the source vectors exactly.
$LeapSecondTable = @(
  @("1972-01-01T00:00:00Z", 10), @("1972-07-01T00:00:00Z", 11),
  @("1973-01-01T00:00:00Z", 12), @("1974-01-01T00:00:00Z", 13),
  @("1975-01-01T00:00:00Z", 14), @("1976-01-01T00:00:00Z", 15),
  @("1977-01-01T00:00:00Z", 16), @("1978-01-01T00:00:00Z", 17),
  @("1979-01-01T00:00:00Z", 18), @("1980-01-01T00:00:00Z", 19),
  @("1981-07-01T00:00:00Z", 20), @("1982-07-01T00:00:00Z", 21),
  @("1983-07-01T00:00:00Z", 22), @("1985-07-01T00:00:00Z", 23),
  @("1988-01-01T00:00:00Z", 24), @("1990-01-01T00:00:00Z", 25),
  @("1991-01-01T00:00:00Z", 26), @("1992-07-01T00:00:00Z", 27),
  @("1993-07-01T00:00:00Z", 28), @("1994-07-01T00:00:00Z", 29),
  @("1996-01-01T00:00:00Z", 30), @("1997-07-01T00:00:00Z", 31),
  @("1999-01-01T00:00:00Z", 32), @("2006-01-01T00:00:00Z", 33),
  @("2009-01-01T00:00:00Z", 34), @("2012-07-01T00:00:00Z", 35),
  @("2015-07-01T00:00:00Z", 36), @("2017-01-01T00:00:00Z", 37)
)

function Get-TaiMinusUtcSeconds([long]$UnixMs) {
  $Offset = $null
  foreach ($Entry in $LeapSecondTable) {
    $EffectiveMs = [DateTimeOffset]::Parse([string]$Entry[0], $Invariant,
      [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
    if ($UnixMs -lt $EffectiveMs) { break }
    $Offset = [int]$Entry[1]
  }
  if ($null -eq $Offset) {
    throw "Deep ephemeris generation supports UTC conversion from 1972 onward."
  }
  return $Offset
}

function Get-TdbMinusTtSeconds([double]$JdTt) {
  $MeanAnomalyRad = (357.53 + 0.9856003 * ($JdTt - 2451545.0)) * [Math]::PI / 180
  return 0.001657 * [Math]::Sin($MeanAnomalyRad) +
    0.00001385 * [Math]::Sin(2 * $MeanAnomalyRad)
}

function Convert-JdTdbToUnixMsUtc([double]$JdTdb) {
  $PseudoUnixMs = ($JdTdb - 2440587.5) * 86400000
  $ApproxUtcMs = [long][Math]::Round($PseudoUnixMs - 70000)
  $TaiMinusUtc = Get-TaiMinusUtcSeconds $ApproxUtcMs
  $TdbMinusUtc = $TaiMinusUtc + 32.184 + (Get-TdbMinusTtSeconds $JdTdb)
  return [long][Math]::Round($PseudoUnixMs - $TdbMinusUtc * 1000)
}

function Convert-UnixMsUtcToJdTdb([long]$UnixMs) {
  $JdUtc = 2440587.5 + $UnixMs / 86400000.0
  $TaiMinusUtc = Get-TaiMinusUtcSeconds $UnixMs
  $JdTt = $JdUtc + ($TaiMinusUtc + 32.184) / 86400.0
  return $JdUtc + ($TaiMinusUtc + 32.184 + (Get-TdbMinusTtSeconds $JdTt)) / 86400.0
}

function Set-ObjectProperty([object]$Object, [string]$Name, [object]$Value) {
  $Property = $Object.PSObject.Properties[$Name]
  if ($null -eq $Property) { $Object | Add-Member -NotePropertyName $Name -NotePropertyValue $Value }
  else { $Property.Value = $Value }
}

function Normalize-LegacyRecordTimes([object]$Record) {
  if ($null -eq $Record) { return }
  $Samples = @(Get-ObjectProperty $Record "samples")
  foreach ($Sample in $Samples) {
    if ($Sample.Count -lt 1) { continue }
    $JdTdb = 2440587.5 + [long]$Sample[0] / 86400000.0
    $Sample[0] = Convert-JdTdbToUnixMsUtc $JdTdb
  }
  if ($Samples.Count) {
    Set-ObjectProperty $Record "startMs" ([long]$Samples[0][0])
    Set-ObjectProperty $Record "stopMs" ([long]$Samples[$Samples.Count - 1][0])
  }
}

function Write-GeneratedPayload([object]$Payload) {
  $Header = @"
/* GENERATED by get_deep_ephemerides.ps1 from NASA/JPL Horizons.
 * Do not hand-edit. Positions are ephemerides/predictions, not telemetry.
 * Mission-aware cadence ranges from 15 minutes to 6 hours.
 * Source JDTDB epochs are converted to UTC instants before storage.
 * Reference bodies use bounded Sun-centered position and velocity samples.
 * Never extrapolate beyond each record's startMs/stopMs coverage. */
"use strict";
globalThis.MTP_DEEP_EPHEMERIS =
"@
  $Json = $Payload | ConvertTo-Json -Depth 9 -Compress
  $null = $Json | ConvertFrom-Json
  $TextOut = $Header + $Json + ";`n"
  $TempPath = $OutputPath + ".tmp"
  [IO.File]::WriteAllText($TempPath, $TextOut, [Text.UTF8Encoding]::new($false))
  Move-Item -LiteralPath $TempPath -Destination $OutputPath -Force
}

function Read-ExistingPayload {
  if (-not (Test-Path -LiteralPath $OutputPath)) { return $null }
  $Source = [IO.File]::ReadAllText($OutputPath)
  $Match = [regex]::Match($Source,
    '(?s)globalThis\.MTP_DEEP_EPHEMERIS\s*=\s*(\{.*\})\s*;\s*$')
  if (-not $Match.Success) {
    throw "Could not parse the existing generated bundle at $OutputPath."
  }
  return ($Match.Groups[1].Value | ConvertFrom-Json)
}

$ExistingPayload = Read-ExistingPayload
if ([string]::IsNullOrWhiteSpace($StartDate)) {
  $StartDate = [string](Get-ObjectProperty $ExistingPayload "startDate")
  if ([string]::IsNullOrWhiteSpace($StartDate)) { $StartDate = "2026-06-27" }
}
if ([string]::IsNullOrWhiteSpace($StopDate)) {
  $StopDate = [string](Get-ObjectProperty $ExistingPayload "stopDate")
  if ([string]::IsNullOrWhiteSpace($StopDate)) { $StopDate = "2026-08-26" }
}

if ($Mode -eq "ReferencesOnly" -and $null -eq $ExistingPayload) {
  throw "ReferencesOnly mode requires an existing generated bundle to preserve."
}

if ($NormalizeExistingTimeScale) {
  if ($null -eq $ExistingPayload) { throw "No existing bundle is available to normalize." }
  $AlreadyUtc = [string](Get-ObjectProperty $ExistingPayload "sampleTimeScale") -eq "UTC"
  $ExistingTrajectories = Get-ObjectProperty $ExistingPayload "trajectories"
  $ExistingReferences = Get-ObjectProperty $ExistingPayload "referenceBodies"
  if (-not $AlreadyUtc) {
    foreach ($Property in @($ExistingTrajectories.PSObject.Properties)) {
      Normalize-LegacyRecordTimes $Property.Value
    }
    foreach ($Property in @($ExistingReferences.PSObject.Properties)) {
      Normalize-LegacyRecordTimes $Property.Value
    }
  }
  Set-ObjectProperty $ExistingPayload "sourceTimeScale" "TDB"
  Set-ObjectProperty $ExistingPayload "sampleTimeScale" "UTC"
  Set-ObjectProperty $ExistingPayload "timeConversion" "JDTDB to UTC using leap seconds and the standard TDB-TT periodic approximation"
  Set-ObjectProperty $ExistingPayload "referenceSourceTimeScale" "TDB"
  Set-ObjectProperty $ExistingPayload "referenceSampleTimeScale" "UTC"
  $CoverageRecords = @($ExistingTrajectories.PSObject.Properties | ForEach-Object { $_.Value })
  if ($CoverageRecords.Count) {
    $CoverageStart = ($CoverageRecords | ForEach-Object { [long]$_.startMs } | Measure-Object -Minimum).Minimum
    $CoverageStop = ($CoverageRecords | ForEach-Object { [long]$_.stopMs } | Measure-Object -Maximum).Maximum
    Set-ObjectProperty $ExistingPayload "coverageStartUtc" ([DateTimeOffset]::FromUnixTimeMilliseconds($CoverageStart).UtcDateTime.ToString("o"))
    Set-ObjectProperty $ExistingPayload "coverageStopUtc" ([DateTimeOffset]::FromUnixTimeMilliseconds($CoverageStop).UtcDateTime.ToString("o"))
  }
  $ReferenceRecords = @($ExistingReferences.PSObject.Properties | ForEach-Object { $_.Value })
  if ($ReferenceRecords.Count) {
    $ReferenceStart = ($ReferenceRecords | ForEach-Object { [long]$_.startMs } | Measure-Object -Minimum).Minimum
    $ReferenceStop = ($ReferenceRecords | ForEach-Object { [long]$_.stopMs } | Measure-Object -Maximum).Maximum
    Set-ObjectProperty $ExistingPayload "referenceCoverageStartUtc" ([DateTimeOffset]::FromUnixTimeMilliseconds($ReferenceStart).UtcDateTime.ToString("o"))
    Set-ObjectProperty $ExistingPayload "referenceCoverageStopUtc" ([DateTimeOffset]::FromUnixTimeMilliseconds($ReferenceStop).UtcDateTime.ToString("o"))
  }
  Write-GeneratedPayload $ExistingPayload
  $TimeAction = if ($AlreadyUtc) { "Verified" } else { "Normalized" }
  Write-Host ($TimeAction + " JDTDB-to-UTC metadata in $OutputPath.")
  exit 0
}
if ($null -ne $ExistingPayload -and
    [string](Get-ObjectProperty $ExistingPayload "sampleTimeScale") -ne "UTC") {
  throw "Existing bundle has legacy JDTDB labels. Run once with -NormalizeExistingTimeScale before refreshing it."
}

function Encode([string]$Value) {
  return [Uri]::EscapeDataString($Value)
}

function Get-MissionCadence([string]$Group) {
  # Local orbiters need several samples per revolution. More slowly varying
  # heliocentric missions stay compact while still improving on daily vectors.
  switch ($Group) {
    "LUNAR"       { return [pscustomobject]@{ Label = "15 m"; Seconds = 900 } }
    "MARS"        { return [pscustomobject]@{ Label = "30 m"; Seconds = 1800 } }
    "OBSERVATORY" { return [pscustomobject]@{ Label = "3 h";  Seconds = 10800 } }
    default        { return [pscustomobject]@{ Label = "6 h";  Seconds = 21600 } }
  }
}

function Get-TrajectoryClass([string]$TargetId) {
  # Ulysses NAIF ID -55 uses the mission-history SPK through 2050, but the
  # official kernel comment says its predicted portion begins 2009-06-30.
  # Keep this narrow verified exception; Horizons coverage is not telemetry.
  if ($TargetId -eq "-55") { return "PREDICTED" }
  return "CURRENT_WINDOW"
}

function Invoke-HorizonsRows([string]$TargetId, [string]$StepSize,
    [long]$StartUtcMs, [long]$StopUtcMs) {
  $StartTdb = "JD" + (Convert-UnixMsUtcToJdTdb $StartUtcMs).ToString("F9", $Invariant)
  $StopTdb = "JD" + (Convert-UnixMsUtcToJdTdb $StopUtcMs).ToString("F9", $Invariant)
  $Query = @(
    "format=json",
    "COMMAND=$(Encode "'$TargetId'")",
    "EPHEM_TYPE=VECTORS",
    "CENTER=$(Encode "'500@10'")",
    "START_TIME=$(Encode "'$StartTdb'")",
    "STOP_TIME=$(Encode "'$StopTdb'")",
    "STEP_SIZE=$(Encode "'$StepSize'")",
    "REF_PLANE=$(Encode "'ECLIPTIC'")",
    "REF_SYSTEM=$(Encode "'ICRF'")",
    "VEC_TABLE=2",
    "VEC_CORR=$(Encode "'NONE'")",
    "OUT_UNITS=$(Encode "'KM-S'")",
    "CSV_FORMAT=YES",
    "OBJ_DATA=NO"
  ) -join "&"
  $Response = Invoke-RestMethod -Uri ("https://ssd.jpl.nasa.gov/api/horizons.api?" + $Query) -Method Get
  $Text = [string]$Response.result
  $A = $Text.IndexOf('$$SOE')
  $B = $Text.IndexOf('$$EOE')
  if ($A -lt 0 -or $B -le $A) {
    return [pscustomobject]@{ Rows = @(); Text = $Text }
  }

  $Rows = @()
  $Block = $Text.Substring($A + 5, $B - $A - 5)
  foreach ($Line in ($Block -split "`r?`n")) {
    if ($Line -notmatch '^\s*\d') { continue }
    $Part = $Line.Split(',')
    if ($Part.Count -lt 8) { continue }
    try {
      $Jd = [double]::Parse($Part[0].Trim(), $Invariant)
      $Rows += ,@(
        (Convert-JdTdbToUnixMsUtc $Jd),
        [Math]::Round([double]::Parse($Part[2].Trim(), $Invariant), 3),
        [Math]::Round([double]::Parse($Part[3].Trim(), $Invariant), 3),
        [Math]::Round([double]::Parse($Part[4].Trim(), $Invariant), 3),
        [Math]::Round([double]::Parse($Part[5].Trim(), $Invariant), 9),
        [Math]::Round([double]::Parse($Part[6].Trim(), $Invariant), 9),
        [Math]::Round([double]::Parse($Part[7].Trim(), $Invariant), 9)
      )
    } catch {
      Write-Warning "Could not parse a vector row for target $TargetId."
    }
  }
  return [pscustomobject]@{ Rows = $Rows; Text = $Text }
}

function Get-HorizonsRows([string]$TargetId, [string]$StepSize) {
  $StartUtcMs = [DateTimeOffset]::Parse($StartDate, $Invariant,
    [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
  $StopUtcMs = [DateTimeOffset]::Parse($StopDate, $Invariant,
    [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
  # Horizons rejects an entire request when either endpoint crosses the
  # loaded SPK coverage, even when most of the requested release window is
  # valid. Retry inside each source-reported boundary and retain only that
  # bounded interval; the runtime already refuses to extrapolate beyond it.
  $RetryStartUtcMs = $StartUtcMs
  $RetryStopUtcMs = $StopUtcMs
  $BoundaryMarginMs = 300000
  for ($AttemptIndex = 0; $AttemptIndex -lt 3; $AttemptIndex++) {
    $Attempt = Invoke-HorizonsRows $TargetId $StepSize $RetryStartUtcMs $RetryStopUtcMs
    if (@($Attempt.Rows).Count -ge 2) { return @($Attempt.Rows) }
    $Changed = $false
    if ($Attempt.Text -match '(?:before|prior to) A\.D\. ([0-9]{4}-[A-Z]{3}-[0-9]{2} [0-9:.]+) TDB') {
      $Boundary = [DateTimeOffset]::Parse($Matches[1], $Invariant,
        [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
      $NextStartUtcMs = [Math]::Max($RetryStartUtcMs, $Boundary + $BoundaryMarginMs)
      if ($NextStartUtcMs -ne $RetryStartUtcMs) { $RetryStartUtcMs = $NextStartUtcMs; $Changed = $true }
    }
    if ($Attempt.Text -match 'after A\.D\. ([0-9]{4}-[A-Z]{3}-[0-9]{2} [0-9:.]+) TDB') {
      $Boundary = [DateTimeOffset]::Parse($Matches[1], $Invariant,
        [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
      $NextStopUtcMs = [Math]::Min($RetryStopUtcMs, $Boundary - $BoundaryMarginMs)
      if ($NextStopUtcMs -ne $RetryStopUtcMs) { $RetryStopUtcMs = $NextStopUtcMs; $Changed = $true }
    }
    if ($RetryStartUtcMs -ge $RetryStopUtcMs -or -not $Changed) { return @() }
  }
  return @()
}

$ReferenceDefinitions = @(
  [pscustomobject]@{ BodyId = "mercury";  HorizonsId = 199; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "venus";    HorizonsId = 299; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "earth";    HorizonsId = 399; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "moon";     HorizonsId = 301; Label = "15 m"; Seconds = 900 },
  [pscustomobject]@{ BodyId = "mars";     HorizonsId = 499; Label = "30 m"; Seconds = 1800 },
  [pscustomobject]@{ BodyId = "phobos";   HorizonsId = 401; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "deimos";   HorizonsId = 402; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "jupiter";  HorizonsId = 599; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "io";       HorizonsId = 501; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "europa";   HorizonsId = 502; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "ganymede"; HorizonsId = 503; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "callisto"; HorizonsId = 504; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "saturn";   HorizonsId = 699; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "enceladus";HorizonsId = 602; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "titan";    HorizonsId = 606; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "uranus";   HorizonsId = 799; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "neptune";  HorizonsId = 899; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "triton";   HorizonsId = 801; Label = "3 h";  Seconds = 10800 },
  [pscustomobject]@{ BodyId = "pluto";    HorizonsId = 999; Label = "6 h";  Seconds = 21600 },
  [pscustomobject]@{ BodyId = "charon";   HorizonsId = 901; Label = "3 h";  Seconds = 10800 }
)

function Get-ExistingReference([string]$BodyId) {
  $Bodies = Get-ObjectProperty $ExistingPayload "referenceBodies"
  return Get-ObjectProperty $Bodies $BodyId
}

function Test-UsableReference([object]$Record, [object]$Definition) {
  if ($null -eq $Record) { return $false }
  if ([string](Get-ObjectProperty $Record "horizonsId") -ne [string]$Definition.HorizonsId) { return $false }
  if ([long](Get-ObjectProperty $Record "stepSeconds") -ne [long]$Definition.Seconds) { return $false }
  $Samples = @(Get-ObjectProperty $Record "samples")
  if ($Samples.Count -lt 2) { return $false }
  $First = @($Samples[0])
  $Last = @($Samples[$Samples.Count - 1])
  if ($First.Count -lt 7 -or $Last.Count -lt 7) { return $false }
  try {
    $RecordStart = [long](Get-ObjectProperty $Record "startMs")
    $RecordStop = [long](Get-ObjectProperty $Record "stopMs")
    if ([long]$First[0] -ne $RecordStart -or [long]$Last[0] -ne $RecordStop) { return $false }
    $RequestedStart = [DateTimeOffset]::Parse($StartDate, $Invariant,
      [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
    $RequestedStop = [DateTimeOffset]::Parse($StopDate, $Invariant,
      [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
    return ($RecordStart -le $RequestedStart + 120000 -and $RecordStop -ge $RequestedStop - 120000)
  } catch {
    return $false
  }
}

function Get-ExistingMission([string]$TargetId) {
  $ExistingTrajectories = Get-ObjectProperty $ExistingPayload "trajectories"
  return Get-ObjectProperty $ExistingTrajectories $TargetId
}

function Test-UsableMission([object]$Record, [object]$Cadence) {
  if ($null -eq $Record) { return $false }
  $StepSeconds = [long](Get-ObjectProperty $Record "stepSeconds")
  if ($StepSeconds -le 0 -or $StepSeconds -gt [long]$Cadence.Seconds) { return $false }
  $Samples = @(Get-ObjectProperty $Record "samples")
  if ($Samples.Count -lt 2) { return $false }
  $First = @($Samples[0])
  $Last = @($Samples[$Samples.Count - 1])
  if ($First.Count -lt 7 -or $Last.Count -lt 7) { return $false }
  try {
    $RecordStart = [long](Get-ObjectProperty $Record "startMs")
    $RecordStop = [long](Get-ObjectProperty $Record "stopMs")
    if ([long]$First[0] -ne $RecordStart -or [long]$Last[0] -ne $RecordStop) { return $false }
    $RequestedStart = [DateTimeOffset]::Parse($StartDate, $Invariant,
      [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
    $RequestedStop = [DateTimeOffset]::Parse($StopDate, $Invariant,
      [Globalization.DateTimeStyles]::AssumeUniversal).ToUnixTimeMilliseconds()
    return ($RecordStart -le $RequestedStart + 120000 -and $RecordStop -ge $RequestedStop - 120000)
  } catch {
    return $false
  }
}

$Trajectories = [ordered]@{}
$Failed = [Collections.Generic.List[string]]::new()
$MissionPreserved = [Collections.Generic.List[string]]::new()

if ($Mode -eq "Full") {
  if (-not (Test-Path -LiteralPath $CatalogPath)) {
    throw "Missing $CatalogPath"
  }
  $CatalogSource = [IO.File]::ReadAllText($CatalogPath)
  $Targets = [regex]::Matches($CatalogSource,
    'mission\(\s*(-?\d+),\s*"[^"]+",\s*"([A-Z_]+)"') |
    ForEach-Object {
      [pscustomobject]@{ Id = $_.Groups[1].Value; Group = $_.Groups[2].Value }
    }

  if ($Targets.Count -ne 100 -or ($Targets.Id | Select-Object -Unique).Count -ne 100) {
    throw "Expected 100 unique Horizons targets, found $($Targets.Count)."
  }

  $Index = 0
  foreach ($Target in $Targets) {
    $Index++
    $Id = $Target.Id
    $Cadence = Get-MissionCadence $Target.Group
    Write-Progress -Activity "Generating Deep 100 ephemerides" -Status "$Index / 100 (Horizons $Id)" -PercentComplete $Index
    $Rows = @()
    $FailureMessage = $null
    try {
      $Rows = @(Get-HorizonsRows $Id $Cadence.Label)
      if ($Rows.Count -le 1) { $FailureMessage = "no coverage" }
    } catch {
      $FailureMessage = $_.Exception.Message
    }
    if ($Rows.Count -gt 1) {
      $MissionRecord = [ordered]@{
        generatedAt = (Get-Date).ToUniversalTime().ToString("o")
        startMs = $Rows[0][0]
        stopMs = $Rows[$Rows.Count - 1][0]
        stepSeconds = $Cadence.Seconds
        trajectoryClass = Get-TrajectoryClass $Id
        samples = $Rows
      }
      if ($Id -eq "-55") {
        $MissionRecord.predictionStartDate = "2009-06-30"
        $MissionRecord.predictionSource = "NAIF ulysses_1990_2009_2050.bsp mission-history kernel comment"
      }
      $Trajectories[$Id] = $MissionRecord
      Write-Host ("[{0,3}/100] {1,9}  {2,5} vectors @ {3}" -f $Index, $Id, $Rows.Count, $Cadence.Label)
    } else {
      $ExistingMission = Get-ExistingMission $Id
      if (Test-UsableMission $ExistingMission $Cadence) {
        $Trajectories[$Id] = $ExistingMission
        $MissionPreserved.Add($Id)
        Write-Host ("[{0,3}/100] {1,9}  preserving existing coverage" -f $Index, $Id)
      } else {
        $Failed.Add($Id)
        Write-Host ("[{0,3}/100] {1,9}  unavailable: {2}" -f $Index, $Id, $FailureMessage)
      }
    }
    if ($DelayMs -gt 0) { Start-Sleep -Milliseconds $DelayMs }
  }
  Write-Progress -Activity "Generating Deep 100 ephemerides" -Completed

  if ($Trajectories.Count -eq 0) {
    throw "Horizons returned no usable trajectories; the existing generated bundle was not replaced."
  }

  # `unavailable` means absent from the resulting bundle, not merely absent
  # from this network attempt. Rebuild it after per-target preservation.
  $Failed.Clear()
  foreach ($Target in $Targets) {
    if (-not $Trajectories.Contains([string]$Target.Id)) { $Failed.Add([string]$Target.Id) }
  }

  $ExistingTrajectories = Get-ObjectProperty $ExistingPayload "trajectories"
  $ExistingCount = if ($null -eq $ExistingTrajectories) { 0 } else {
    @($ExistingTrajectories.PSObject.Properties).Count
  }
  $SameWindow = $null -ne $ExistingPayload -and
    [string](Get-ObjectProperty $ExistingPayload "startDate") -eq $StartDate -and
    [string](Get-ObjectProperty $ExistingPayload "stopDate") -eq $StopDate
  if ($SameWindow -and $Trajectories.Count -lt $ExistingCount) {
    throw "Mission coverage regressed from $ExistingCount to $($Trajectories.Count) for the same window; the existing generated bundle was not replaced."
  }
}

$ReferenceBodies = [ordered]@{}
$ReferenceFailed = [Collections.Generic.List[string]]::new()
$ReferencePreserved = [Collections.Generic.List[string]]::new()
$ReferenceIndex = 0
foreach ($Definition in $ReferenceDefinitions) {
  $ReferenceIndex++
  $BodyId = $Definition.BodyId
  Write-Progress -Activity "Generating reference-body ephemerides" -Status "$ReferenceIndex / $($ReferenceDefinitions.Count) ($BodyId)" -PercentComplete (($ReferenceIndex / $ReferenceDefinitions.Count) * 100)
  $Rows = @()
  $ErrorMessage = $null
  try {
    $Rows = @(Get-HorizonsRows ([string]$Definition.HorizonsId) $Definition.Label)
  } catch {
    $ErrorMessage = $_.Exception.Message
  }

  if ($Rows.Count -gt 1) {
    $ReferenceBodies[$BodyId] = [ordered]@{
      horizonsId = $Definition.HorizonsId
      startMs = $Rows[0][0]
      stopMs = $Rows[$Rows.Count - 1][0]
      stepSeconds = $Definition.Seconds
      samples = $Rows
    }
    Write-Host ("[ref {0,2}/{1}] {2,-10} {3,5} vectors @ {4}" -f $ReferenceIndex, $ReferenceDefinitions.Count, $BodyId, $Rows.Count, $Definition.Label)
  } else {
    $ExistingReference = Get-ExistingReference $BodyId
    if (Test-UsableReference $ExistingReference $Definition) {
      $ReferenceBodies[$BodyId] = $ExistingReference
      $ReferencePreserved.Add($BodyId)
      Write-Host ("[ref {0,2}/{1}] {2,-10} preserving existing coverage" -f $ReferenceIndex, $ReferenceDefinitions.Count, $BodyId)
    } else {
      $ReferenceFailed.Add($BodyId)
      if ($null -eq $ErrorMessage) { $ErrorMessage = "no coverage" }
      Write-Host ("[ref {0,2}/{1}] {2,-10} unavailable: {3}" -f $ReferenceIndex, $ReferenceDefinitions.Count, $BodyId, $ErrorMessage)
    }
  }
  if ($DelayMs -gt 0) { Start-Sleep -Milliseconds $DelayMs }
}
Write-Progress -Activity "Generating reference-body ephemerides" -Completed

foreach ($RequiredBody in @("moon", "mars")) {
  if ($null -eq $ReferenceBodies[$RequiredBody]) {
    throw "Required reference body '$RequiredBody' has no usable coverage; the existing generated bundle was not replaced."
  }
}

$ReferenceGeneratedAt = (Get-Date).ToUniversalTime().ToString("o")
$ReferenceMetadata = [ordered]@{
  referenceGeneratedAt = $ReferenceGeneratedAt
  referenceSource = "NASA/JPL Horizons release-generated vectors"
  referenceCenter = "500@10 (Sun center)"
  referenceFrame = "ICRF / ecliptic J2000"
  referenceUnits = "km and km/s"
  referenceSourceTimeScale = "TDB"
  referenceSampleTimeScale = "UTC"
  referenceStartDate = $StartDate
  referenceStopDate = $StopDate
  referenceRequested = $ReferenceDefinitions.Count
  referenceCovered = $ReferenceBodies.Count
  referenceCadencePolicy = [ordered]@{
    MOON = "15 m"
    MARS = "30 m"
    MOONS = "3 h"
    PLANETS = "6 h"
  }
  referenceUnavailable = $ReferenceFailed.ToArray()
  referencePreserved = $ReferencePreserved.ToArray()
  referenceBodies = $ReferenceBodies
}

if ($Mode -eq "ReferencesOnly") {
  $ReferencePropertyNames = @($ReferenceMetadata.Keys)
  $Payload = [ordered]@{}
  foreach ($Property in $ExistingPayload.PSObject.Properties) {
    if ($ReferencePropertyNames -notcontains $Property.Name) {
      $Payload[$Property.Name] = $Property.Value
    }
  }
  foreach ($Name in $ReferenceMetadata.Keys) {
    $Payload[$Name] = $ReferenceMetadata[$Name]
  }
} else {
  $CoverageStartMs = ($Trajectories.Values | ForEach-Object { [long]$_.startMs } |
    Measure-Object -Minimum).Minimum
  $CoverageStopMs = ($Trajectories.Values | ForEach-Object { [long]$_.stopMs } |
    Measure-Object -Maximum).Maximum
  $Payload = [ordered]@{
    generatedAt = (Get-Date).ToUniversalTime().ToString("o")
    source = "NASA/JPL Horizons release-generated vectors"
    center = "500@10 (Sun center)"
    frame = "ICRF / ecliptic J2000"
    units = "km and km/s"
    sourceTimeScale = "TDB"
    sampleTimeScale = "UTC"
    timeConversion = "JDTDB to UTC using leap seconds and the standard TDB-TT periodic approximation"
    startDate = $StartDate
    stopDate = $StopDate
    coverageStartUtc = [DateTimeOffset]::FromUnixTimeMilliseconds($CoverageStartMs).UtcDateTime.ToString("o")
    coverageStopUtc = [DateTimeOffset]::FromUnixTimeMilliseconds($CoverageStopMs).UtcDateTime.ToString("o")
    requested = 100
    covered = $Trajectories.Count
    cadencePolicy = [ordered]@{
      LUNAR = "15 m"
      MARS = "30 m"
      OBSERVATORY = "3 h"
      DEFAULT = "6 h"
    }
    unavailable = $Failed.ToArray()
    trajectories = $Trajectories
  }
  foreach ($Name in $ReferenceMetadata.Keys) {
    $Payload[$Name] = $ReferenceMetadata[$Name]
  }
}

Write-GeneratedPayload $Payload

Write-Host "Wrote $OutputPath"
if ($Mode -eq "Full") {
  Write-Host "$($Trajectories.Count)/100 targets have coverage from $StartDate through $StopDate."
  if ($Failed.Count) { Write-Host ("Unavailable targets: " + ($Failed -join ", ")) }
  if ($MissionPreserved.Count) { Write-Host ("Preserved mission targets: " + ($MissionPreserved -join ", ")) }
} else {
  Write-Host "Preserved all existing mission trajectories and mission metadata."
}
Write-Host "$($ReferenceBodies.Count)/$($ReferenceDefinitions.Count) reference bodies have bounded coverage."
if ($ReferenceFailed.Count) { Write-Host ("Unavailable reference bodies: " + ($ReferenceFailed -join ", ")) }
if ($ReferencePreserved.Count) { Write-Host ("Preserved reference bodies: " + ($ReferencePreserved -join ", ")) }
