param(
  [string]$InputPath,
  [string]$OutputPath
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
if ([string]::IsNullOrWhiteSpace($InputPath)) {
  $InputPath = Join-Path $Root "js\deep-space-ephemeris.js"
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
  $OutputPath = Join-Path $Root "js\planner-ephemeris-data.js"
}

if (-not (Test-Path -LiteralPath $InputPath)) {
  throw "The generated Horizons bundle was not found at $InputPath."
}

$Source = [IO.File]::ReadAllText($InputPath)
$Match = [regex]::Match($Source,
  '(?s)globalThis\.MTP_DEEP_EPHEMERIS\s*=\s*(\{.*\})\s*;\s*$')
if (-not $Match.Success) {
  throw "Could not parse the generated Horizons bundle at $InputPath."
}
$Bundle = $Match.Groups[1].Value | ConvertFrom-Json
if ($null -eq $Bundle.referenceBodies) {
  throw "The input bundle does not contain generated reference-body vectors."
}

$Bodies = [ordered]@{}
$Total = 0
$CommonStartMs = [long]::MinValue
$CommonStopMs = [long]::MaxValue
foreach ($Property in @($Bundle.referenceBodies.PSObject.Properties)) {
  $Record = $Property.Value
  $Samples = @($Record.samples)
  if ($Samples.Count -lt 2) { continue }
  $Bodies[$Property.Name] = [ordered]@{
    epochUnit = "unix-ms"
    source = [string]$Bundle.source
    sourceId = [string]$Record.horizonsId
    cadenceSeconds = [double]$Record.stepSeconds
    samples = $Samples
  }
  $Total += $Samples.Count
  $CommonStartMs = [Math]::Max($CommonStartMs, [long]$Samples[0][0])
  $CommonStopMs = [Math]::Min($CommonStopMs, [long]$Samples[$Samples.Count - 1][0])
}
if (-not $Bodies.Count) { throw "No bounded reference-body tables were available." }
if ($CommonStartMs -gt $CommonStopMs) {
  throw "The reference-body tables do not share a common bounded coverage window."
}
$CoverageStartUtc = [DateTimeOffset]::FromUnixTimeMilliseconds($CommonStartMs).UtcDateTime.ToString("o")
$CoverageStopUtc = [DateTimeOffset]::FromUnixTimeMilliseconds($CommonStopMs).UtcDateTime.ToString("o")

$Payload = [ordered]@{
  source = [string]$Bundle.source
  generatedAt = [string]$Bundle.generatedAt
  center = [string]$Bundle.referenceCenter
  frame = [string]$Bundle.referenceFrame
  timeScale = [string]$Bundle.referenceSampleTimeScale
  sourceTimeScale = [string]$Bundle.referenceSourceTimeScale
  timeConversion = [string]$Bundle.timeConversion
  units = [string]$Bundle.referenceUnits
  epochUnit = "unix-ms"
  coverageStartUtc = $CoverageStartUtc
  coverageStopUtc = $CoverageStopUtc
  generatedFrom = (Split-Path -Leaf $InputPath)
  bodies = $Bodies
}

$Json = $Payload | ConvertTo-Json -Depth 9 -Compress
$null = $Json | ConvertFrom-Json
$Header = @"
/* GENERATED by get_planner_ephemerides.ps1 from the bounded NASA/JPL Horizons
 * reference-body vectors in js/deep-space-ephemeris.js. Do not hand-edit.
 * Source JDTDB epochs were converted to UTC by the upstream generator.
 * Cubic-Hermite consumers must not extrapolate outside per-body coverage. */
"use strict";
globalThis.MTP_PLANNER_EPHEMERIS =
"@
$Text = $Header + $Json + ";`n"
$Temp = $OutputPath + ".tmp"
[IO.File]::WriteAllText($Temp, $Text, [Text.UTF8Encoding]::new($false))
Move-Item -LiteralPath $Temp -Destination $OutputPath -Force
Write-Host ("Wrote {0} Horizons body tables / {1} rows to {2}." -f $Bodies.Count, $Total, $OutputPath)
